c = input('Digite algo: ')
print(type(c))
print('só tem espaço? {}'.format(c.isspace()))
print('é um numero? {}'.format(c.isnumeric()))
print('é alfabetico? {}'.format(c.isalpha()))
print('é alfanumerico? {}'.format(c.isalnum()))
print('esta em maiusculo? {}'.format(c.isupper()))
print('esta em minuscula? {}'.format(c.islower()))
print('esta capitalizada? {}'.format(c.isidentifier()))
